export interface TarotCard {
  name: string;
  image: string;
}

export const TAROT_DECK: TarotCard[] = [
  { name: "愚者", image: "../images/愚人.png" },
  { name: "魔术师", image: "../images/魔术师.png" },
  { name: "女祭司", image: "../images/女祭司.png" },
  { name: "女皇", image: "../images/女皇.png" },
  { name: "皇帝", image: "../images/皇帝.png" },
  { name: "教皇", image: "../images/教皇.png" },
  { name: "恋人", image: "../images/恋人.png" },
  { name: "战车", image: "../images/战车.png" },
  { name: "力量", image: "../images/力量.png" },
  { name: "隐士", image: "../images/隐士.png" },
  { name: "命运之轮", image: "../images/命运之轮.png" },
  { name: "正义", image: "../images/正义.png" },
  { name: "倒吊人", image: "../images/倒吊人.png" },
  { name: "死神", image: "../images/死神.jpg" },
  { name: "节制", image: "../images/节制.png" },
  { name: "恶魔", image: "../images/恶魔.png" },
  { name: "高塔", image: "../images/高塔.png" },
  { name: "星星", image: "../images/星星.png" },
  { name: "月亮", image: "../images/月亮.png" },
  { name: "太阳", image: "../images/太阳.png" },
  { name: "审判", image: "../images/审判.png" },
  { name: "世界", image: "../images/世界.png" },
  { name: "权杖1", image: "../images/权杖1.png"},
  { name: "权杖2", image: "../images/权杖2.png"},
  { name: "权杖3", image: "../images/权杖3.png"},
  { name: "权杖4", image: "../images/权杖4.png"},
  { name: "权杖5", image: "../images/权杖5.png"},
  { name: "权杖6", image: "../images/权杖6.png"},
  { name: "权杖7", image: "../images/权杖7.png"},
  { name: "权杖8", image: "../images/权杖8.png"},
  { name: "权杖9", image: "../images/权杖9.png"},
  { name: "权杖10", image: "../images/权杖10.png"},
  { name: "权杖国王", image: "../images/权杖国王.png"},
  { name: "权杖王后", image: "../images/权杖王后.png"},
  { name: "权杖骑士", image: "../images/权杖骑士.png"},
  { name: "权杖侍卫", image: "../images/权杖侍卫.png"},
  { name: "圣杯1", image: "../images/圣杯1.png"},
  { name: "圣杯2", image: "../images/圣杯2.png"},
  { name: "圣杯3", image: "../images/圣杯3.png"},
  { name: "圣杯4", image: "../images/圣杯4.png"},
  { name: "圣杯5", image: "../images/圣杯5.png"},
  { name: "圣杯6", image: "../images/圣杯6.png"},
  { name: "圣杯7", image: "../images/圣杯7.png"},
  { name: "圣杯8", image: "../images/圣杯8.png"},
  { name: "圣杯9", image: "../images/圣杯9.png"},
  { name: "圣杯10", image: "../images/圣杯10.png"},
  { name: "圣杯国王", image: "../images/圣杯国王.png"},
  { name: "圣杯王后", image: "../images/圣杯王后.png"},
  { name: "圣杯骑士", image: "../images/圣杯骑士.png"},
  { name: "圣杯侍卫", image: "../images/圣杯侍卫.png"},
  { name: "宝剑1", image: "../images/宝剑1.png"},
  { name: "宝剑2", image: "../images/宝剑2.png"},
  { name: "宝剑3", image: "../images/宝剑3.png"},
  { name: "宝剑4", image: "../images/宝剑4.png"},
  { name: "宝剑5", image: "../images/宝剑5.png"},
  { name: "宝剑6", image: "../images/宝剑6.png"},
  { name: "宝剑7", image: "../images/宝剑7.png"},
  { name: "宝剑8", image: "../images/宝剑8.png"},
  { name: "宝剑9", image: "../images/宝剑9.png"},
  { name: "宝剑10", image: "../images/宝剑10.png"},
  { name: "宝剑国王", image: "../images/宝剑国王.png"},
  { name: "宝剑王后", image: "../images/宝剑王后.png"},
  { name: "宝剑骑士", image: "../images/宝剑骑士.png"},
  { name: "宝剑侍卫", image: "../images/宝剑侍卫.png"},
  { name: "星币1", image: "../images/星币1.png"},
  { name: "星币2", image: "../images/星币2.png"},
  { name: "星币3", image: "../images/星币3.png"},
  { name: "星币4", image: "../images/星币4.png"},
  { name: "星币5", image: "../images/星币5.png"},
  { name: "星币6", image: "../images/星币6.png"},
  { name: "星币7", image: "../images/星币7.png"},
  { name: "星币8", image: "../images/星币8.png"},
  { name: "星币9", image: "../images/星币9.png"},
  { name: "星币10", image: "../images/星币10.png"},
  { name: "星币国王", image: "../images/星币国王.png"},
  { name: "星币王后", image: "../images/星币王后.png"},
  { name: "星币骑士", image: "../images/星币骑士.png"},
  { name: "星币侍卫", image: "../images/星币侍卫.png"}
];

export const ZODIAC_SIGNS = [
  "白羊座", "金牛座", "双子座", "巨蟹座", "狮子座", "处女座",
  "天秤座", "天蝎座", "射手座", "摩羯座", "水瓶座", "双鱼座"
];
